
import random
import time
import os
clear = lambda: os.system('cls')
playerpos = 3
coppos = 1
court1 = 0
copposmoove = 0
# note: not all interactions have cutscenes
# Another note: THIS GAME IS CASE SENCETIVE
def jail():
        print()
        print("you can always just escape")
        print("you find out you had a phone on you")
        valg = input("what do you do with your phone? A: Play games. B: call a lawyer C: Call in an intercontinental balistic missile D: order yourself a hammer --> ")
        print()
        if valg == "A":
            print("the guards cought you gaming and took ur phone")
            print()
            print("||   ||    ||||||     ||    ||")
            print(" || ||    ||    ||    ||    ||")
            print("  |||     ||    ||    ||    ||")
            print("  |||      ||||||      ||||||")
            print()
            print("|||||     |||    ||  ||      ||||||  |||| ")
            print("||       || ||   ||  ||      ||      ||  ||")   
            print("|||||   |||||||  ||  ||      ||||    ||  ||")
            print("||      ||   ||  ||  ||      ||      ||  ||") 
            print("||      ||   ||  ||  ||||||  ||||||  |||| ")
            print()  
        if valg == "C":
            print("you called in a missile but forgot your still in the prison and you die to the explodion")
            print()
            print("||   ||    ||||||     ||    ||")
            print(" || ||    ||    ||    ||    ||")
            print("  |||     ||    ||    ||    ||")
            print("  |||      ||||||      ||||||")
            print()
            print("|||||     |||    ||  ||      ||||||  |||| ")
            print("||       || ||   ||  ||      ||      ||  ||")   
            print("|||||   |||||||  ||  ||      ||||    ||  ||")
            print("||      ||   ||  ||  ||      ||      ||  ||") 
            print("||      ||   ||  ||  ||||||  ||||||  |||| ")
            print()  
        if valg == "B":
            court()
        if valg == "D":
            valg = input("what will you destroy? A: the toilet. B: the wall. C: the cell door. -->")
            if valg == "A":
                sewer()
            if valg == "B":
                print("|||         ")
                print(" o          ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("  o         ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("   o        ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("           ")
                print("||| o        ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("           ")
                print("|||         ")
                print("|||  o       ")
                print("|||         ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("           ")
                print("|||         ")
                print("|||         ")
                print("|||   o      ")
                print("|||         ")
                time.sleep(1)
                clear()
                print("|||         ")
                print("           ")
                print("|||         ")
                print("|||         ")
                print("|||         ")
                print("|||   o      ")
                time.sleep(1)
                clear()
                print("         ")
                print("|||           ")
                print("|||         ")
                print("|||         ")
                print("|||   o      ")
                print("|||||||      ")
                time.sleep(1)
                clear()
                print("You landed on a cliff and died")
                print()
                print("||   ||    ||||||     ||    ||")
                print(" || ||    ||    ||    ||    ||")
                print("  |||     ||    ||    ||    ||")
                print("  |||      ||||||      ||||||")
                print()
                print("|||||     |||    ||  ||      ||||||  |||| ")
                print("||       || ||   ||  ||      ||      ||  ||")   
                print("|||||   |||||||  ||  ||      ||||    ||  ||")
                print("||      ||   ||  ||  ||      ||      ||  ||") 
                print("||      ||   ||  ||  ||||||  ||||||  |||| ")
                print()  

            
            if valg == "C":
                jailbreak()

def jailbreak():
    print()
    print("you bust dow the cell dor and stare through the hallway")
    valg3 = input("will you bust down the other inmates doors. A.: yes. B: no --> ")
    if valg3 == "A":
        print("you bust down all the nearby cells.")
        print("it did take its time but it will surly be worth it")
    print("in a hurry you sprint down the hallway")
    print("you see 2 doors.")
    print("one leads to the police cafeteria/office")
    print("the other one to the warden controll room.")
    valg = input("which door do you go through. A: Warden controll room. B: police cafeteria room -->")
    if valg == "A":
        if valg3 == "A":
            print("it seems as the warden room is now heavely guarded by the police")
            print("you and all other innmates are put in solitary untill the next day.")
            jail()
        elif valg3 == "B":
            print("the guards arent currently there")
            print()
            valg = input("what do you do? A: Take The warden keycard. B: Push a button releasing all the prisoners --> ")
            if valg == "A":
                print()
                print("you use the keykard to sneak youself out of the prison.")
                print("you proseed to take the police speedboat and escape")
                True_prison_warden()
            if valg == "B":
                print()
                print("ALL THE PRISONERS ARE RUNNING RAMPAGE!!")
                print("you consider staying to watch the spectical")
                valg = input("A: Stay and watch the chaos persue its F R E E D O M. B: escape through the conviniently placed tunnel -->")
                if valg == "A":
                    print("the police are unable to stop the innmates")
                    print("this is what F R E E D O M must feel like")
                    print()
                    print("nah")
                    ultimate_chaos()
                if valg == "B":
                    print()
                    print("you end up in a lab")
                    print("with curiosity, you press random buttons")
                    print("one of said buttons activates the nuke that was being cunstructed")
                    print("but you are in a safe place from the explodion")
                    time.sleep(10)
                    print("         ")
                    print("           ")
                    print("         ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("         ")
                    print("           ")
                    print("       |  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("         ")
                    print("       |    ")
                    print("      |||  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("       |  ")
                    print("     |||||    ")
                    print("      |||  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("      |||  ")
                    print("    |||||||    ")
                    print("      |||  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("     ||||||  ")
                    print("   ||||||||||    ")
                    print("      |||  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    print("   |||||||||  ")
                    print(" ||||||||||||||    ")
                    print("     |||||  ")
                    print("   ||||||||     ")
                    print("   ||||||||         ")
                    print("|||||||||||||||")
                    time.sleep(1)
                    clear()
                    FINAL_FALLOUT()
    else:
        if valg3 == "B":
            print("all the guards was in the cafeteria")
            print("you and all other innmates are put in solitary untill the next day.")
            jail()
        elif valg3 == "A":
            print("there were no guards in the office room.")
            print("you and the other inmates disguise themselfs as guards and escapes")
            the_bois()

def court():
    global court1
    if court1 == 1:
        print("Didnt we already prove you guilty?")
        jail()
    if court1 == 0:
        print("you call a lawyer")
        print("YOU ARE IN COURT NOW")
        print("Lawyer: the client is compleatly inncoent sir")
        valg = input("what do you bring up? A: self defence. B: hunting license. C: the fact that nobody brought a corpse as proof. --> ")
        print()
        if valg == "A":
            SELF_DEF()
        if valg == "B":
            hunt_100()
        if valg == "C":
            print("Prosecutor: well you litterly killed that bear in sight of one of our cameras")
            print()
            print("Lawer: well, I got nothing here")
            print()
            print("Judge: well if there is no arguement then its settled")
            jail()
# the endings
def legal_ending(): # dont think court works like this tbh or who knows (Main Ending)
    print()
    print("you won")
    print("Ending 1: Legal Ending")
    print("you survived the most legal way")

def True_prison_warden(): # the warden is gonna have a big problem (Main Ending)
    print()
    print("you win")
    print("Ending 3: True Prison Warden Ending")
    print("You are the one in controll of everybody's F R E E D O M now")

def ultimate_chaos(): # dont let the prisoners go on a rampage (Main Ending)
    print()
    print("You win")
    print("Ending 4: Ultimate chaos Ending")
    print("the prison battle royale.")
    print()
    print("Hopefully not comming")
    print()
    print("surly not")
    print()
    print("I wouldn't make that")
    print()
    print("would not...")
    print()
    print("ever....")
    print()
    print("right....")

def FINAL_FALLOUT(): # tjernobyl 2: electic boogaloo (Main Ending)
    print()
    print("You win")
    print("Ending 5: FINAL FALLOUT Ending")
    print("none of thoose prisoners survived")

def the_bois(): # The bois (Main Ending)
    print()
    print("You win")
    print("Ending 6: The Bois")
    print("you escape with the BOIS")

def runaway(): # I would have had problems imagening 6 endings for the runaway path too, so minigame instead (Main Ending)
    print()
    print("You Win")
    print("Ending 7: Runaway Ending")
    print("You make it away and can begin a new life as a goat farmer in Pakistan")

def simulation(): # it was never real and N E V E R   W I L L   B E (Secret Ending)
    print()
    print("You win")
    print("Secret Ending: The Simulation")
    print("WELCOME TO THE REAL WORLD KID")

def absolute_genesis(): # O U T S T A N I N G   M O O V E (Secret Ending)
    print()
    print("you win...")
    print("Secret Ending: Absolute genesis")
    print("Outstanding Move")
# there are more 4 main endings and 1 more secret ending just put where you obtain them
# enjoy finding them
def SELF_DEF():
    if valg2 == "A": 
        print("Judge: Sir, you litterly dropkicked the bear.")
        print("How is that self defence")
        print()
        print("Lawer: well, the bear attacked them first")
        print()
        print("Prosecutor: they litterly decided to jump on the bear to kill it.")
        print("they probebly had full intent to hurt that bear.")
        print("they would have just kept running if they didnt want the bear dead")
        print()
        print("Judge: well thats that settled")
        print("Lawer: What do you mean settled!!")
        jail()
    
    if valg2 == "B":
        print("Judge: they did use thair second amendment right")
        print("Lawer: Yep")
        print()
        print("Prosecutor: Dont think that right counts for other animals than humans, sir")
        print()
        print("Lawer: it still is self defence")
        print("Judge: Correct")
        print("Prosecutor: Bruhhhh")
        legal_ending()

def hunt_100():
    if valg2 == "A": 
        print("Judge: Sir, you litterly dropkicked the bear.")
        print("Dont think hunting licences work like that")
        print()
        print("Lawer: well, the client is a little wild")
        print()
        print("Prosecutor: if they were hunting properly they would bring a gun.")
        print("isnt it kinda animal abuse.")
        print()
        print("Lawer: dont think so if the bear died immidietly")
        print()
        print("Prosecutor: But still")
        print("they could never have garanteed that 1 hit K.O.")
        print("so they got lucky there")
        print()
        print("Judge: what point are you proving?")
        print()
        print("Prosecutor: they probebly intended to bring it pain")
        print()
        print("Judge: Well thats settled then")
        print("Lawer: Doubt anybody will learn anything from this")
        print()
        print("OBJECTION!!")
        print("Prosecutor: WHAT!?!")
        print()
        print("Lawer: they never did the crime though")
        print("they did successfully hunt the bear")
        print()
        print("Judge: Guess they are innocent then")
        print("Prosecutor: I dont get paid enough for this")
        legal_ending()

    
    if valg2 == "B":
        print("Judge: Good point")
        print()
        print("Prosecutor: what argumenbt do I even have.....")
        print()
        print("Lawer: thair actions compleately legal")
        print("Judge: Correct")
        print("Prosecutor: Bruhhhh")
        legal_ending()

def sewer():
    loop = 1
    print("you get the hammer and decide to destroy the toilet")
    print()
    print("you hop into the sewer")
    print("it smells like rats")
    print()
    print("you get an odd feeling")
    print("You sence an odd presence")
    while loop >= 0:
        input("P R O S E E D")
        print()
        if loop == 1:
            print("you keep on going but dont feel like you are getting anywhere")
            print()
            print("how odd")
            print()
            loop = random.randint(0,6)
        elif loop == 2:
            print("you keep on going but you feel like you are getting slower")
            print()
            print("how odd")
            print()
            loop = random.randint(0,6)
        elif loop == 3:
            print("you keep on going but you feel like you are slowly dying")
            print()
            print("how odd")
            print()
            loop = random.randint(0,6)
        elif loop == 4:
            print("you keep on going but you feel like you are beeing cunsumed by the rats")
            print()
            print("how odd")
            print()
            loop = random.randint(0,6)
        elif loop == 5:
            print("P A I N")
            print(" P A I N")
            print("Y O U. F E E L. T H E. N O T H I N G N E S S.")
            print(" P A I N")
            print("P A I N")
            print()
            loop = random.randint(0,6)
        elif loop == 6:
            print("you keep on going but you feel like you are beeing watched by the unknown pressence")
            print()
            print("how unfortunate")
            print()
            loop = random.randint(0,6)
        elif loop == 0:
            loop = -1
    while loop <= 400:
        rng = random.randint(1,100)
        print("P R O S E E D")
        loop = loop + 1
        time.sleep(0.0001)
    while loop >= 310:
        print()
        loop = loop - 1
    if rng == 9:
        clear()
        print("|||        || ")
        print("   o       || ")
        print("|||        || ")
        print("|||        || ")
        print("|||        || ")
        print("|||        || ")
        time.sleep(1)
        clear()
        print("|||        || ")
        print("           || ")
        print("|||  o     || ")
        print("|||        || ")
        print("|||        || ")
        print("|||        || ")
        time.sleep(1)
        clear()
        print("|||        || ")
        print("           || ")
        print("|||        || ")
        print("|||    o   || ")
        print("|||        || ")
        print("|||        || ")
        time.sleep(1)
        clear()
        print("|||        || ")
        print("           || ")
        print("|||        || ")
        print("|||        || ")
        print("|||     o  || ")
        print("|||        || ")
        time.sleep(1)
        clear()
        print("|||        || ")
        print("           || ")
        print("|||        || ")
        print("|||        || ")
        print("|||        || ")
        print("|||     o  || ")
        time.sleep(1)
        clear()
        print("You wake up in a whirlpool")
        print("and suddenly...")
        print()
        print("you are in a lab..")
        print()
        print("Scientist 1: how did the simulation go?")
        print()
        print("Scientist 2: uhh... they are awake!!")
        print("Scientist 1: HUH!!!")
        print()
        print("Scientist 2: welcome to the real world kid.")
        print("Scientist 1: the simulation must have bugged out")
        print("you werent supposed to be able to fall off there")
        simulation()
    import room1
    
def runminigame():
    global playerpos
    global coppos
    coppos = int(coppos)
    playerpos = int(playerpos)
    inpoot = 0
    print("The police are currently 2 spaced behind you")
    print("you can only moove 1-3 spaces at a time")
    print("but you cant go 4 tiles away from thair next spot")
    print("that is because there are helicopters ahead")
    print("so make sure theres at max 2 empty spaces (with nerither you or the cops)")
    inoooot = input("understand?")
    if inoooot == "no" or "No" or "NO":
        print()
        print("What do you mean no!?")
        print("fine u win")
        print("im not dealing with this")
        print()
        print("You Won?")
        print("Secret Ending: N O")
        print("Im not forcing you to understand")
        exit()
    while playerpos <= 30:
        inpoot = 0
        copposmoove = random.randint(0,3)
        coppos = coppos + copposmoove
        print(f"the cops plan to moove", copposmoove, "spaces")
        while inpoot != 1 and inpoot != 2 and inpoot != 3:
            inpoot = int(input("how many spaces do you move: "))
        playerpos = playerpos + int(inpoot)
        if coppos >= playerpos:
            print("the cops cought up with you and cought you")
            print()
            print()
            print("||   ||    ||||||     ||    ||")
            print(" || ||    ||    ||    ||    ||")
            print("  |||     ||    ||    ||    ||")
            print("  |||      ||||||      ||||||")
            print()
            print("|||||     |||    ||  ||      ||||||  |||| ")
            print("||       || ||   ||  ||      ||      ||  ||")   
            print("|||||   |||||||  ||  ||      ||||    ||  ||")
            print("||      ||   ||  ||  ||      ||      ||  ||") 
            print("||      ||   ||  ||  ||||||  ||||||  |||| ")
            print()  
            exit()
        if playerpos >= coppos + 4:
            print("the cop helicopters catch you and cought you")
            print()
            print("||   ||    ||||||     ||    ||")
            print(" || ||    ||    ||    ||    ||")
            print("  |||     ||    ||    ||    ||")
            print("  |||      ||||||      ||||||")
            print()
            print("|||||     |||    ||  ||      ||||||  |||| ")
            print("||       || ||   ||  ||      ||      ||  ||")   
            print("|||||   |||||||  ||  ||      ||||    ||  ||")
            print("||      ||   ||  ||  ||      ||      ||  ||") 
            print("||      ||   ||  ||  ||||||  ||||||  |||| ")
            print()            
            exit()
        print("they dont reach you")
        time.sleep(2)
        clear()
    print("You get away")
    runaway()

print("you are casually walking through an abandoned town as one does")

print("a bear approaches you")

valg = input("What do? A: 1 v 1 the bear B: R U N --> ")
print()
if valg == "A":
    print("the bear had an intercontinental balistic missile and used it on you")
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o   M ")
    print("|||||||||||||||")
    time.sleep(1)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("    o M ")
    print("|||||||||||||||")
    time.sleep(1)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("     oM ")
    print("|||||||||||||||")
    time.sleep(1)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("       W  ")
    print("     o ")
    print("|||||||||||||||")
    time.sleep(1)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("     o   M")
    print("|||||||||||||||")
    time.sleep(0.2)
    clear()
    print("     |   ")
    print("           ")
    print("         ")
    print("         ")
    print("     o   M")
    print("|||||||||||||||")
    time.sleep(0.2)
    clear()
    print("        ")
    print("     |      ")
    print("         ")
    print("         ")
    print("     o   M")
    print("|||||||||||||||")
    time.sleep(0.2)
    clear()
    print("        ")
    print("           ")
    print("     |    ")
    print("         ")
    print("     o   M")
    print("|||||||||||||||")
    time.sleep(0.2)
    clear()
    print("        ")
    print("           ")
    print("         ")
    print("     |    ")
    print("     o   M")
    print("|||||||||||||||")
    time.sleep(0.2)
    clear()
    print("        ")
    print("           ")
    print("         ")
    print("         ")
    print("     |   M")
    print("|||||||||||||||")
    time.sleep(1)
    clear()
    print()
    print("||   ||    ||||||     ||    ||")
    print(" || ||    ||    ||    ||    ||")
    print("  |||     ||    ||    ||    ||")
    print("  |||      ||||||      ||||||")
    print()
    print("|||||     |||    ||  ||      ||||||  |||| ")
    print("||       || ||   ||  ||      ||      ||  ||")   
    print("|||||   |||||||  ||  ||      ||||    ||  ||")
    print("||      ||   ||  ||  ||      ||      ||  ||") 
    print("||      ||   ||  ||  ||||||  ||||||  |||| ")
    print()
if valg == "B":
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o   M ")
    print("|||||||||||||||")
    time.sleep(0.5)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o    M ")
    print("|||||||||||||||")
    time.sleep(0.5)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o     M ")
    print("|||||||||||||||")
    time.sleep(0.5)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o      M ")
    print("|||||||||||||||")
    time.sleep(0.5)
    clear()
    print("         ")
    print("           ")
    print("         ")
    print("         ")
    print("   o        M ")
    print("|||||||||||||||")
    time.sleep(0.5)
    clear()
    print("Good. but the bear is still chasing you")

    valg2 = input("how get stop the bear? A: Dropkick the bear. B: bring out that gun you keep for self defence --> ")
    print()
    if valg2 == "A":
        print("you successfully kill the bear as it hasnt learned your moveset yet.")
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o        M ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("     o    ")
        print("            M ")
        print("|||||||||||||||     ")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("      o    ")
        print("            M ")
        print("|||||||||||||||     ")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("        o    ")
        print("            M ")
        print("|||||||||||||||     ")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("          o    ")
        print("            M ")
        print("|||||||||||||||     ")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("                ")
        print("            o w")
        print("|||||||||||||||     ")
        time.sleep(1)
        clear()
    if valg2 == "B":
        print("you use ur 2nd amendment right and killed the bear")
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o -       M ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o   -     M ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o     -   M ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o        -M ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
        print("         ")
        print("           ")
        print("         ")
        print("         ")
        print("   o        W ")
        print("|||||||||||||||")
        time.sleep(1)
        clear()
    print()
    
    print("you suddenly get captured and are on your way to a helicopter")
    print("they are trying to carry you to a prison")
    valg3 = input("how do you deal with this issue? A: Break free and run. B: accept ur fate --> ")
    print()
    if valg3 == "A":
        print("You break free successfully and are on the run now")
        clear()
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||  O   |||")
        print("|||      |||")
        print("|||      |||")
        time.sleep(1)
        clear()
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||  O   |||")
        print("|||      |||")
        print("|||      |||")
        
        time.sleep(1)
        clear()
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||    O |||")
        print("|||      |||")
        print("|||      |||")
        
        time.sleep(1)
        clear()
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||      |||")
        print("|||  O   |||")
        print("|||      |||")
        time.sleep(1)
        clear()
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||      |||")
        print("|||      |||")
        print("|||   O  |||")
        time.sleep(1)
        clear()
        print("|||      |||")
        print("|||      |||")
        print("||| o  o |||")
        print("|||      |||")
        print("|||      |||")
        print("|||      |||")
        print("|||      |||")
        time.sleep(1)
        clear()
        print("You are on the run now")
        runminigame()
    if valg3 == "B":
        jail()
if valg == "C":
    print("Pretty sure that wasnt even an option")
    print("The bear got so cunfused it died.")
    absolute_genesis()